---
title: "Week 7"
author: "Rachael Valdez"
date: "10/4/2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r test1}
test1 = "The current year is 2016"
#exercise 1
my_pattern = "[xqb]"
my_pattern = "[0-9]"
grepl(pattern = my_pattern, test1)
#exercise 2
gregexpr(my_pattern, test1)
#output = gregexpr(my_pattern, test1) #output puts value on top right dashboard into a list
temp = gregexpr(my_pattern, test1)
string_position = temp[[1]]

gregexpr("[[:blank:]]", test1)
#exercise3
grepl(pattern = "[[:upper:][:digit:]]", test1)
#exercie4
temp = regexpr(pattern = "[[:blank:]]", test1)
first_space = temp[[1]][1] #first slot and first entry
first_space

#exercise5
my_pattern = "[[:lower:]].[[:digit:]]"
#my_pattern = "[[:lower:].[:digit:]]" #does this do the same as line above? NO
grepl(my_pattern, test1)
#exercise6
loc = gregexpr(my_pattern, test1)[[1]][1] #this accomplishes same as below two lines of code, shortcut
#temp = gregexpr(my_pattern, test1)
#loc = temp[[1]] [1]

#exercise7
my_pattern = "\\s[[:lower:]][[:lower:]]\\s"
loc = gregexpr(my_pattern, test1)[[1]][1]
#exercise8
text2 = sub(my_pattern, replacement = " is not ", test1)

my_pattern = "\\s[[:lower:]]{2}\\s" #same as above
gregexpr(my_pattern, test1)[[1]][1]

#exercise9
my_pattern = "\\d{4}"
temp = gregexpr(my_pattern, text2)
string_pos4 = temp[[1]][1]

#exercise 10

substr(text2, start = string_pos4, stop = string_pos4 + 1)

```

```{r HW}


```
